version: "3"

services:

  cblite:
    image: cblite
    build: ./cblite
    platform: linux/amd64

  cb-server:
    image: cb-server
    build: ./cb-server
    ports:
      - "8091-8094:8091-8094"
      - 11210:11210

  sync-gateway:
    image: local-sg
    build:
      context: sg
      ssh:
        - default
    ports:
      - 4984:4984
      - 4985:4985
    depends_on:
      cb-server:
        condition: service_healthy
