version: "3"

services:

  cblite:
    image: cblite
    build: ./cblite
    platform: linux/amd64

  cb-server:
    image: cb-server
    build: ./cb-server
    ports:
      - "8091-8094:8091-8094"
      - 11210:11210
    healthcheck:
      test: "curl -u Administrator:password --fail --connect-timeout 5 --max-time 2 --retry 20 --retry-delay 0 --retry-max-time 120 http://localhost:8091/pools/default/buckets || exit 1"
      retries: 10
      interval: 5s

  sync-gateway:
    image: local-sg
    build: sg
    ports:
      - 4984:4984
    depends_on:
      cb-server:
        condition: service_healthy
